#ifndef INF_VST_SYNTH_INSTRUMENT_PLUGIN_HPP
#define INF_VST_SYNTH_INSTRUMENT_PLUGIN_HPP

// Don't forget to update the versioned guids, too.
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_VERSION "1.1"
#if INF_VERSIONED
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_NAME "InfernalSynth 1.1"
#elif !INF_VERSIONED
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_NAME "InfernalSynth Generic"
#else
#error
#endif

#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_COMPANY_WEB "Infernal"
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_COMPANY_NAME "Infernal"
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_COMPANY_MAIL "sjoerdvankreel@gmail.com"
#define INF_VST_INFERNAL_SYNTH_INSTRUMENT_CONTROLLER_NAME "InfernalSynthController"

#endif // INF_VST_SYNTH_INSTRUMENT_PLUGIN_HPP
