#ifndef INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_PLUGIN_HPP
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_PLUGIN_HPP

#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_VERSION "1.3"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_VERSION_MAJOR 1
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_VERSION_MINOR 3
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_NAME "Infernal Synth"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_VENDOR "Sjoerd van Kreel"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_ID "sjoerdvankreel.infernal_synth"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_URL "https://sjoerdvankreel.github.io/infernal-synth"

#endif // INF_PLUGIN_INFERNAL_SYNTH_FORMAT_CLAP_PLUGIN_HPP