#ifndef INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_PLUGIN_HPP
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_PLUGIN_HPP

#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_VERSION "1.3"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_VERSION_MAJOR 1
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_VERSION_MINOR 3
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_VERSION_REVISION 0
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_VENDOR_NAME "Sjoerd van Kreel"

#if INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_FX
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_NAME "InfernalSynth FX 1.3"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_CONTROLLER_NAME "InfernalSynthFXController"
#elif (!INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_FX)
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_NAME "InfernalSynth 1.3"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_CONTROLLER_NAME "InfernalSynthController"
#else 
#error
#endif

#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_COMPANY_WEB "Infernal"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_COMPANY_NAME "Infernal"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_ORIG_FILE_NAME "InfernalSynth.vst3"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_LEGAL_COPYRIGHT "(C) Sjoerd van Kreel"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_COMPANY_MAIL "sjoerdvankreel@gmail.com"
#define INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_LEGAL_TRADEMARKS "VST is a trademark of Steinberg Media Technologies GmbH"

#endif // INF_PLUGIN_INFERNAL_SYNTH_FORMAT_VST3_PLUGIN_HPP
