#ifndef INF_BASE_VST_UI_VST_UI_EDITOR_HPP
#define INF_BASE_VST_UI_VST_UI_EDITOR_HPP

#include <inf.base.ui/shared/plugin_ui_editor.hpp>
#include <inf.base.vst.ui/vst_ui_controller.hpp>

#include <vstgui/plugin-bindings/vst3editor.h>
#include <vector>

namespace inf::base::vst::ui {

class vst_ui_controller;

// Vst3 editor with basic support for declarative parameter 
// visibility. See param_ui_descriptor.relevant_if_param.
// Json files (.uidesc) are generated by ui generator project.
// Note: this class breaks the vst3 gui editor. Remove 
// onViewAdded/onViewRemoved/update_dependent_visibility if you need
// to play around with the editor. Conditional visibility 
// obviously won't work then.
class vst_ui_editor: 
public VSTGUI::VST3Editor,
public inf::base::ui::plugin_ui_editor
{
  using CFrame = VSTGUI::CFrame;
  using CPoint = VSTGUI::CPoint;
  using MouseEvent = VSTGUI::MouseEvent;
  using ParamID = Steinberg::Vst::ParamID;
  using KeyboardEvent = VSTGUI::KeyboardEvent;
  using EditController = Steinberg::Vst::EditController;

  void popup_context_menu();

public:
  vst_ui_editor(vst_ui_controller* controller, UTF8StringPtr template_name,
    UTF8StringPtr xml_file, inf::base::topology_info const* topology);

  bool find_parameter(CPoint const& pos);
  void onKeyboardEvent(KeyboardEvent& event, CFrame* which_frame);

  void onViewAdded(CFrame* view_frame, CView* view) override;
  void onViewRemoved(CFrame* view_frame, CView* view) override;
  void onMouseEvent(MouseEvent& event, CFrame* which_frame) override;
  bool PLUGIN_API open(void* parent, const PlatformType& type) override;

  CFrame* frame() const override { return getFrame(); }
  void attachedToParent() override { dynamic_cast<vst_ui_controller&>(*getController()).view_attached(this); }
  void removedFromParent() override { dynamic_cast<vst_ui_controller&>(*getController()).view_removed(this); }
  Steinberg::tresult PLUGIN_API find_parameter(CPoint const& pos, Steinberg::Vst::ParamID& id) { return findParameter(pos.x, pos.y, id); }
};

// Allow opening the context menu by ctrl+m,
// since not all hosts get the right-clicking right.
class vst_ui_editor_keyboard_hook :
public VSTGUI::IKeyboardHook
{
  using CFrame = VSTGUI::CFrame;
  using KeyboardEvent = VSTGUI::KeyboardEvent;
private:
  vst_ui_editor* const _editor;
public:
  vst_ui_editor_keyboard_hook(vst_ui_editor* editor): _editor(editor) {}
  void onKeyboardEvent(KeyboardEvent& event, CFrame* frame) override { _editor->onKeyboardEvent(event, frame); }
};

} // namespace inf::base::vst::ui
#endif // INF_BASE_VST_UI_VST_UI_EDITOR_HPP
